[package]
name = "rust-game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15", features = ["jpeg"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
noise = "0.9"
hashbrown = "0.15"
bevy_animation = "0.15.0"
futures = "0.3"
